@startuml Mengelola Kategori Santri

|Admin|
start

:Lihat Daftar Kategori;

|Sistem|
:Tampilkan:
• Nama Kategori
• Tarif SPP
• Jumlah Santri;

|Admin|
if (Aksi?) then (Tambah/Edit)
    :Isi/Ubah Data Kategori;
    
    |Sistem|
    :Simpan Perubahan;

else (Hapus)
    :Klik Hapus & Konfirmasi;
    
    |Sistem|
    :Hapus Kategori;
endif

:Tampilkan Daftar Terbaru;

stop

@enduml
