@startuml Aktivitas Wali Santri

|Wali Santri|
start

:Masuk ke Sistem;

|Sistem|
:Tampilkan Data Santri:
----
• Nama & NIS
• Status Tagihan
• Total Tunggakan;

|Wali Santri|
if (Banyak Santri?) then (Ya)

    :Pilih Santri;
else (Tidak)
endif

:Pilih Menu;

if (Menu yang Dipilih?) then (Tagihan)
    |Sistem|
    :Tampilkan Tagihan Bulanan;
else (Bayar)
    |Sistem|
    :Tampilkan Form Pembayaran;
    
    |Wali Santri|
    :Pilih Metode Bayar;
    
    |Sistem|
    if (Online?) then (Ya)
        :Proses di Payment Gateway;
    else (Tidak)
        :Tampilkan Info Transfer;
    endif
endif

|Sistem|
:Perbarui Status;

|Wali Santri|
:Lihat Hasil;

stop

@enduml
